version: '3'

services:
  frong-bot:
    image: soulsender/frong-bot:latest
    environment:
      - TOKEN=your_token_here
      - OPENAI_KEY=your_api_key_here
    volumes:
      - /frong-data:/app/data
    restart: unless-stopped
    
